services:
  postgres:
    image: postgres:18
    container_name: postgresql18
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${IP_ADDRESS_OPENVPN}:${PUBLISH_PORT_POSTGRES}:5432/tcp"
      - "127.0.0.1:5432:5432/tcp"
    volumes:
      - ./data:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - deb-network
networks:
  deb-network:
    external: true